"""Schema-driven contract test for POST /items.

This file demonstrates how three pieces work together:
1) OpenAPI: machine-readable API contract generated by FastAPI.
2) Hypothesis: property-based test engine that generates many inputs.
3) Schemathesis: bridge between OpenAPI and Hypothesis.

High-level flow:
- FastAPI exposes OpenAPI schema for all routes.
- Schemathesis reads that schema and builds test-case generators.
- Hypothesis executes the test many times with generated cases.
- Each generated response is validated against the OpenAPI contract.
"""

from hypothesis import given, settings
import schemathesis

import app.app1 as app_module
from app.app1 import app1


# Build a schema object from the running ASGI app, not from a static file.
#
# Why this is useful:
# - Always matches the current code.
# - Avoids stale checked-in schema documents.
# - Keeps test setup simple for local practice.
#
# "/openapi.json" is the standard FastAPI OpenAPI endpoint.
schema = schemathesis.openapi.from_asgi("/openapi.json", app1)

# Select one specific operation from the schema.
#
# schema["/items"]["post"] means:
# - path: /items
# - method: POST
#
# This narrows generation to a single consumer-provider interaction.
post_items = schema["/items"]["post"]


# @given(...) comes from Hypothesis.
# It calls this test function repeatedly with generated `case` values.
#
# post_items.as_strategy() is a Schemathesis strategy built from OpenAPI.
# It generates request variants (valid/invalid) based on schema constraints.
@given(case=post_items.as_strategy())

# Keep runtime practical for local learning.
# - max_examples=25: run 25 generated cases
# - deadline=None: disable per-example timing limit to reduce flaky slowdowns
@settings(max_examples=25, deadline=None)
def test_post_items_contract_shape(case):
    # Reset shared in-memory state before each generated example.
    #
    # Why:
    # - POST /items can mutate items_db.
    # - Without reset, one generated case can affect the next case.
    # - Deterministic isolation is critical in property-based testing.
    app_module.items_db = {}

    # Execute the generated request.
    #
    # `case` contains the HTTP method, path, headers, and payload produced
    # from the OpenAPI contract. case.call() sends that request and returns
    # a transport-agnostic response object.
    response = case.call()

    # Validate response against OpenAPI expectations for this operation.
    #
    # This includes checks such as:
    # - status code is documented
    # - response body shape matches response schema (when present)
    # - content type aligns with contract
    case.validate_response(response)

    # Project-specific behavior note:
    # - 201 for accepted, valid creation
    # - 422 for payloads rejected by validation
    #
    # This assertion is intentionally narrow to expected outcomes for this app.
    assert response.status_code in {201, 422}
