#!/bin/bash

for i in {1..5}
do
  echo "Iteration $i"
done

name='Mat'
echo $name

date_command=$(date)
echo $date_command

echo anything

echo ------------

echo Script name: $0
echo "First argument: $1"
echo "Second argument: $2"
echo "Total arguments: $#"

