pipeline {
	agent { label 'local-mn-pc-agent' }

	options {
		buildDiscarder(logRotator(numToKeepStr: '5'))
	}

	parameters {
		string(
			name: 'FOLDER',
			defaultValue: 'T10',
			description: 'For example: T11'
		)

		string(
			name: 'TESTS',
			defaultValue: 'test_4',
			description: 'For example: test_3'
		)
		string(
			name: 'BRANCH',
			defaultValue: 'main',
			description: 'Other e.g. feature'
		)
	}

	environment {
		TESTS = "${params.TESTS}"
		FOLDER = "${params.FOLDER}"
		BRANCH = "${params.BRANCH}"
		VENV_DIR = '.venv'
	}

	stages {
		stage('Checkout') {
			steps {
				// checkout scm
				checkout([
				$class: 'GitSCM',
				branches: [[name: "*/${params.BRANCH}"]],
				doGenerateSubmoduleConfigurations: false,
				extensions: [],
				userRemoteConfigs: scm.userRemoteConfigs
        		])

			}
		}

		stage('Install Dependencies') {
			steps {
				// every run recreates or rewrites the virtual environment structure.
				// on every run checks and installs dependencies every time.
				// That is safe, but it costs time on every build even when nothing changed.
				// 
				// sh '''#!/usr/bin/env bash
				// 	set -euo pipefail
				// 	python3 -m venv "$VENV_DIR"
				// 	. "$VENV_DIR/bin/activate"
				// 	python -m pip install --upgrade pip
				// 	pip install -r r/requirements.txt
				// '''

				// A practical better version is to create the venv only if it does not exist:
				// but still installs requirements every run.
				// 
				// sh '''#!/usr/bin/env bash
				// set -euo pipefail

				// if [[ ! -d "$VENV_DIR" ]]; then
				// 	python3 -m venv "$VENV_DIR"
				// fi

				// . "$VENV_DIR/bin/activate"
				// python -m pip install --upgrade pip
				// pip install -r r/requirements.txt
				// '''

				sh '''#!/usr/bin/env bash
				set -euo pipefail

				if [[ ! -d "$VENV_DIR" ]]; then
					python3 -m venv "$VENV_DIR"
				fi

				. "$VENV_DIR/bin/activate"

				req_hash_file="$VENV_DIR/.requirements.hash"
				current_hash="$(sha256sum r/requirements.txt | awk '{print $1}')"
				previous_hash="$(cat "$req_hash_file" 2>/dev/null || true)"

				if [[ "$current_hash" != "$previous_hash" ]]; then
					python -m pip install --upgrade pip
					pip install -r r/requirements.txt
					printf '%s\n' "$current_hash" > "$req_hash_file"
				fi
				'''
			}
		}

		stage('Run Tests') {
			steps {
				// sh '''#!/usr/bin/env bash
				// 	set -euo pipefail
				// 	. "$VENV_DIR/bin/activate"

				// 	pytest_args=(--junitxml=pytest-report.xml --alluredir=allure-results)
				// 	if [[ -n "$TEST" ]]; then
				// 		read -r -a selected_args <<< "$TEST"
				// 		pytest_args=("${selected_args[@]}" "${pytest_args[@]}")
				// 	fi

				// 	pytest "${pytest_args[@]}"
				// '''
				sh '''
				. "$VENV_DIR/bin/activate"
				bash bash_helper.sh $FOLDER $TESTS
				'''
			}
		}
	}

	post {
		always {
			junit allowEmptyResults: true, testResults: 'pytest-report.xml'
			allure(
				includeProperties: false,
				results: [[path: 'allure-results']]
			)
		}
	}
}