pipeline {
	agent { label 'local-mn-pc-agent' }

	parameters {
		string(
			name: 'FOLDER',
			defaultValue: '',
			description: 'For example: T11'
		)

		string(
			name: 'TESTS',
			defaultValue: '',
			description: 'For example: test_3'
		)
	}

	environment {
		TESTS = "${params.TESTS}"
		FOLDER = "${params.FOLDER}"
		VENV_DIR = '.venv'
	}

	stages {
		stage('Checkout') {
			steps {
				checkout scm
			}
		}

		stage('Install Dependencies') {
			steps {
				sh '''#!/usr/bin/env bash
					set -euo pipefail
					python3 -m venv "$VENV_DIR"
					. "$VENV_DIR/bin/activate"
					python -m pip install --upgrade pip
					pip install -r r/requirements.txt
				'''
			}
		}

		stage('Run Tests') {
			steps {
				// sh '''#!/usr/bin/env bash
				// 	set -euo pipefail
				// 	. "$VENV_DIR/bin/activate"

				// 	pytest_args=(--junitxml=pytest-report.xml --alluredir=allure-results)
				// 	if [[ -n "$TEST" ]]; then
				// 		read -r -a selected_args <<< "$TEST"
				// 		pytest_args=("${selected_args[@]}" "${pytest_args[@]}")
				// 	fi

				// 	pytest "${pytest_args[@]}"
				// '''
				sh '''
				. "$VENV_DIR/bin/activate"
				bash bash_helper.sh $FOLDER $TESTS
				'''
			}
		}
	}

	post {
		always {
			junit allowEmptyResults: true, testResults: 'pytest-report.xml'
			allure(
				includeProperties: false,
				results: [[path: 'allure-results']]
			)
		}
	}
}